---
# This playbook contains common tasks in this role
- name: "install basic utilities - debian"
  tags:
   - configuration
  apt:
    name: ['vim', 'tmux', 'screen', 'iotop', 'htop', 'iftop', 'fish']
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
